[package]
name = "database-engine"
version = "0.1.0"
authors = ["leonchik <leonchik@rit.va>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
